Don't crash if qa_contact field is not present
Avoid this error:
  Error: Error calling tool 'search_issues': 400: JQL search failed:
  'PropertyHolder' object has no attribute 'customfield_12315948'

See also PR #20 where this field was added.